import React from 'react';
import s from './Projects.module.scss'
import {Project} from "./project/Project";
import styleContainer from './../common/styles/Container.module.css'
import {Title} from "../common/components/title/Title";
import social from "../assets/images/social-network.svg"
import todo from "../assets/images/todo-list.webp"

export const Projects = () => {
    const socialNetworkImage = {
        backgroundImage: `url(${social})`,
    };
    const todoListImage = {
        backgroundImage: `url(${todo})`,
    };



    return (
        <div className={s.projectsBlock}>
            <div className={`${styleContainer.container} ${s.projectsContainer}`}>
                <Title title={'Projects'}/>
                <div className={s.projects}>
                    <Project title={'Social network'}
                             style={socialNetworkImage}
                             description={'Diverse and rich experience the new model of organizational activity allows us to assess the importance of further development directions. Everyday practice shows that the constant information and propaganda support of our activities entails the process of introducing and modernizing the positions taken by the participants in relation to the tasks set.'}/>
                    <Project title={'Todo list'}
                             style={todoListImage}
                             description={'When creating the generator, we used a well-known universal speech code. The text is generated by paragraphs randomly from two to ten sentences per paragraph, which makes the text more attractive and lively for visual and auditory perception.'}/>
                </div>
            </div>
        </div>
    );
};

